{
  styx.pipewire._.lowlatency =
    {
      quantum ? 44100,
      rate ? 32,
      ...
    }:
    {
      nixos =
        { pkgs, lib, ... }:
        let
          qr = "${toString quantum}/${toString rate}";
          inherit (lib.generators) toLua;
        in
        {
          services.pipewire = {
            # make sure PipeWire is enabled if the module is imported
            # and low latency is enabledd
            enable = true;

            # write extra config
            extraConfig = {
              pipewire."99-lowlatency" = {
                "context.properties" = {
                  "default.clock.min-quantum" = quantum;
                };

                "module.rt.args" = {
                  "nice.level" = -15;
                  "rt.prio" = 88;
                  "rt.time.soft" = 200000;
                  "rt.time.hard" = 200000;
                };
              };

              pipewire-pulse."99-lowlatency" = {
                "pulse.properties" = {
                  "server.address" = [ "unix:native" ];
                  "pulse.min.req" = qr;
                  "pulse.min.quantum" = qr;
                  "pulse.min.frag" = qr;
                };
              };

              client."99-lowlatency" = {
                "stream.properties" = {
                  "node.latency" = qr;
                  "resample.quality" = 1;
                };
              };
            };

            # ensure WirePlumber is enabled explicitly (defaults to true while PW is enabled)
            # and write extra config to ship low latency rules for alsa
            wireplumber = {
              enable = true;
              configPackages =
                let
                  # generate "matches" section of the rules
                  matches =
                    toLua
                      {
                        multiline = false; # looks better while inline
                        indent = false;
                      }
                      [
                        [
                          [
                            "node.name"
                            "matches"
                            "alsa_output.*"
                          ]
                        ]
                      ]; # nested lists are to produce `{{{ }}}` in the output

                  # generate "apply_properties" section of the rules
                  apply_properties = toLua { } {
                    "audio.format" = "S32LE";
                    "audio.rate" = rate * 2;
                    "api.alsa.period-size" = 2;
                  };
                in
                [
                  (pkgs.writeTextDir "share/lowlatency.lua.d/99-alsa-lowlatency.lua" ''
                    -- Generated by nix-gaming
                    alsa_monitor.rules = {
                      {
                        matches = ${matches};
                        apply_properties = ${apply_properties};
                      }
                    }
                  '')
                ];
            };
          };
        };
    };
}

