# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  carapace = {
    pname = "carapace";
    version = "56a43de1f57d5487979d6fc336a33d1076dfae29";
    src = fetchFromGitHub {
      owner = "carapace-sh";
      repo = "carapace-bin";
      rev = "56a43de1f57d5487979d6fc336a33d1076dfae29";
      fetchSubmodules = false;
      sha256 = "sha256-qBGEQUB2DxjQcUDnCIiL6RhNe7WV2y6w5uKiaWql3hE=";
    };
    date = "2025-06-27";
  };
  mpris-scrobbler = {
    pname = "mpris-scrobbler";
    version = "4862b85ff7bd58ce72022eaf74463aea0f99d04e";
    src = fetchFromGitHub {
      owner = "mariusor";
      repo = "mpris-scrobbler";
      rev = "4862b85ff7bd58ce72022eaf74463aea0f99d04e";
      fetchSubmodules = false;
      sha256 = "sha256-VYWS9OletI4QAC07rRuXvncDqUEG7YZRpVtsx500N9c=";
    };
    date = "2025-06-18";
  };
  xsstrike = {
    pname = "xsstrike";
    version = "73d103ce9162f2edc40ebee808f302625dc90eb0";
    src = fetchFromGitHub {
      owner = "boffman";
      repo = "XSStrike";
      rev = "73d103ce9162f2edc40ebee808f302625dc90eb0";
      fetchSubmodules = false;
      sha256 = "sha256-I1QOvup07JeiXZYgoF0rxlEoMI398y3qEYC6qQ2x+l0=";
    };
    date = "2025-05-04";
  };
}
