# Opacity
window.opacity: 1.0

font:
    normal:
        family: JetBrainsMono Nerd Font
        style: regular
    bold:
        family: JetBrainsMono Nerd Font
        style: regular
    italic:
        family: JetBrainsMono Nerd Font
        style: regular
    bold_italic:
        family: JetBrainsMono Nerd Font
        style: regular
    size: 12
    offset:
      x: 0
      y: 1

window:
    padding:
        x: 6
        y: 3
env:
  TERM: xterm-256color


# Catppuccin!
colors:
  # Default colors
  primary:
    background: '0x1E1D2F'
    foreground: '0xD9E0EE'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1E1D2F'
    cursor: '0xF5E0DC'

  # Normal colors
  normal:
    black:   '0x6E6C7E'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan:    '0x89DCEB'
    white:   '0xD9E0EE'

  # Bright colors
  bright:
    black:   '0x988BA2'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan:    '0x89DCEB'
    white:   '0xD9E0EE'

  indexed_colors:
    - { index: 16, color: '0xF8BD96' }
    - { index: 17, color: '0xF5E0DC' }
      
# One Dark! 
#colors:
#  primary:
#    background: '#282c34'
#    foreground: '#bbc2cf'
#  cursor:
#    text: CellBackground
#    cursor: '#528bff'
#  selection:
#    text: CellForeground
#    background: '#3e4451'
#  normal:
#    black:   '#1c1f24'
#    red:     '#ff6c6b'
#    green:   '#98be65'
#    yellow:  '#da8548'
#    blue:    '#51afef'
#    magenta: '#c678dd'
#    cyan:    '#5699af'
#    white:   '#bbc2cf'
#  bright:
#    black:   '#5b6268'
#    red:     '#da8548'
#    green:   '#4db5bd'
#    yellow:  '#ecbe7b'
#    blue:    '#3071db'   # This is 2257a0 in Doom Emacs but dt lightened it.
#    magenta: '#a9a1e1'
#    cyan:    '#46d9ff'
#    white:   '#dfdfdf'
